# Generated by Django 3.2b1 on 2021-03-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_auto_20210313_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'managed': False, 'ordering': ['stakeholder', 'id']},
        ),
        migrations.AlterModelOptions(
            name='sistema',
            options={'managed': False, 'ordering': ['stakeholder', 'titulo']},
        ),
    ]
