# Generated by Django 3.2b1 on 2021-03-13 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0003_auto_20210313_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxonomia', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=150)),
                ('cadastro', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'db_table': 'parametro',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
