# Generated by Django 3.2b1 on 2021-03-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0004_parametro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametro',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': 'Parâmetro', 'verbose_name_plural': 'Parâmetros'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'managed': False, 'ordering': ['stakeholder', 'id'], 'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='sistema',
            options={'managed': False, 'ordering': ['stakeholder', 'titulo'], 'verbose_name': 'Sistema', 'verbose_name_plural': 'Sistemas'},
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'managed': False, 'ordering': ['nome'], 'verbose_name': 'Stakeholder', 'verbose_name_plural': 'Stakeholders'},
        ),
    ]
